# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_extendrAltintTest_wrappers", use_symbols = TRUE, package_name = "extendrAltintTest")

#' @docType package
#' @usage NULL
#' @useDynLib extendrAltintTest, .registration = TRUE
NULL

#' @export
get_intrange <- function() .Call(wrap__get_intrange)

